In [15]:
import pandas as pd
import os

In [16]:
gpt5_base_input_dir = "../assets/raw_data/gpt_5_1_raw"
gpt5_output_dir = "../assets/data_processed/gpt_5_1"

gpt5mini_base_input_dir = "../assets/raw_data/gpt_5_mini_raw"
gpt5mini_output_dir = "../assets/data_processed/gpt_5_mini"

In [17]:
gpt5_excel_path = os.path.join(gpt5_base_input_dir, "experiment_summary_merged.xlsx")
gpt5mini_excel_path = os.path.join(gpt5mini_base_input_dir, "experiment_summary_merged.xlsx")

In [18]:
# Wczytanie danych gpt
df_gpt = pd.read_excel(gpt5_excel_path)
print(f"Wczytano {len(df_gpt)} wierszy danych dla GPT-5.1")

Wczytano 800 wierszy danych dla GPT-5.1

In [19]:
# Wczytanie danych gpt_mini
df_mini = pd.read_excel(gpt5mini_excel_path)
print(f"Wczytano {len(df_mini)} wierszy danych dla GPT-5-Mini")

Wczytano 799 wierszy danych dla GPT-5-Mini

# --- PREPROCESSING ---

In [20]:
# Drop unused columns
df_gpt.drop(columns=["total_cost_usd","execution_result", "final_code"], inplace=True)
df_mini.drop(columns=["total_cost_usd","execution_result", "final_code"], inplace=True)

In [21]:
def round_numeric_values(x, ndigits=2):
    try:
        val = float(x)
        return round(val, ndigits)
    except (ValueError, TypeError):
        return x

In [22]:
# Zaokrąglanie wartości funkcji celu
df_gpt["ground_truth_answer"] = df_gpt["ground_truth_answer"].apply(round_numeric_values)
df_gpt["agent_objective_value"] = df_gpt["agent_objective_value"].apply(round_numeric_values)
# zaokrąglanie czasu
df_gpt["latency_sec"] = df_gpt["latency_sec"].apply(round_numeric_values, ndigits=3)
print("Preprocessing zakończony dla GPT-5.1")

Preprocessing zakończony dla GPT-5.1

In [23]:
# Zmiana nazwy kolumn
df_mini['model'] = 'GPT-5-Mini'
df_gpt['model'] = 'GPT-5.1'

In [24]:
df_gpt.head()

,architecture,model,problem_id,status,prompt_tokens,completion_tokens,total_tokens,latency_sec,agent_objective_value,ground_truth_answer
0,2-agent,GPT-5.1,nl4opt_test_0,success,1072,1023,2095,14.335,1160.00,1160.0
1,2-agent,GPT-5.1,nl4opt_test_1,success,2107,2002,4109,28.866,350.00,350.0
2,2-agent,GPT-5.1,nl4opt_test_2,success,1070,1056,2126,15.979,100.00,100.0
3,2-agent,GPT-5.1,nl4opt_test_3,success,1062,986,2048,16.282,7.00,7.0
4,2-agent,GPT-5.1,nl4opt_test_4,success,845,804,1649,11.600,327.66,327.66

In [25]:
# Zaokrąglanie wartości funkcji celu
df_mini["ground_truth_answer"] = df_mini["ground_truth_answer"].apply(round_numeric_values)
df_mini["agent_objective_value"] = df_mini["agent_objective_value"].apply(round_numeric_values)
# zaokrąglanie czasu
df_mini["latency_sec"] = df_mini["latency_sec"].apply(round_numeric_values, ndigits=3)
print("Preprocessing zakończony dla GPT-5-Mini")

Preprocessing zakończony dla GPT-5-Mini

In [26]:
df_mini.head()

,architecture,model,problem_id,status,prompt_tokens,completion_tokens,total_tokens,latency_sec,agent_objective_value,ground_truth_answer
0,2-agent,GPT-5-Mini,nl4opt_test_9,success,782,2474,3256,42.061,950.0,950.0
1,2-agent,GPT-5-Mini,nl4opt_test_17,success,870,2631,3501,45.026,1400.0,1400.0
2,2-agent,GPT-5-Mini,nl4opt_test_2,success,967,2874,3841,45.321,100.0,100.0
3,2-agent,GPT-5-Mini,nl4opt_test_1,success,945,2701,3646,46.588,350.0,350.0
4,2-agent,GPT-5-Mini,nl4opt_test_5,success,961,2752,3713,50.190,215000.0,215000.0

In [27]:
print("Zapisywanie danych GPT-5.1 do pliku")
gpt5_output_excel_path = os.path.join(gpt5_output_dir, "experiment_summary.xlsx")
df_gpt.to_excel(gpt5_output_excel_path, index=False)

Zapisywanie danych GPT-5.1 do pliku

In [28]:
print("Zapisywanie danych GPT-5-Mini do pliku")
gpt5mini_output_excel_path = os.path.join(gpt5mini_output_dir, "experiment_summary.xlsx")
df_mini.to_excel(gpt5mini_output_excel_path, index=False)

Zapisywanie danych GPT-5-Mini do pliku